2024-08-10 14:27:38,257 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\nt\PycharmProjects\pythonProject\.venv\tests_12_4.py", line 22, in test_run
    run2 = Runner( 2,5 )
           ^^^^^^^^^^^^^
  File "C:\Users\nt\PycharmProjects\pythonProject\.venv\rt_with_exceptions.py", line 9, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-08-10 14:27:38,259 | WARNING | Неверная -скорость для Runner 
Traceback (most recent call last):
  File "C:\Users\nt\PycharmProjects\pythonProject\.venv\tests_12_4.py", line 10, in test_walk
    run1 = Runner( "run1",-5 )
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nt\PycharmProjects\pythonProject\.venv\rt_with_exceptions.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас увы {speed}')
ValueError: Скорость не может быть отрицательной, сейчас увы -5
